import type { GameMap } from './types';

// Castle Field topology, transcribed from the publisher's setup and region diagrams.
// Coordinates and visual treatment are original; the three bridge bases are not
// connected directly to each other. The two central four-base regions score 2.
export const CASTLE_MAP: GameMap = {
  id: 'castle-field',
  name: '성채 평원',
  width: 1100,
  height: 640,
  medalTarget: 7,
  theme: 'castle',
  description: '갈림길과 세 다리에서 훈장을 두고 맞붙는 기본 전장.',
  specialDescription: '북 거점에 병정을 놓으면 다른 거점의 내 병정 하나를 손으로 데려옵니다.',
  nodes: [
    { id: 'hq-blue', label: '파랑 본부', x: 110, y: 320, kind: 'hq', ownerIndex: 0 },
    { id: 'blue-top', label: '서쪽 위 관문', x: 110, y: 110, kind: 'base' },
    { id: 'blue-bottom', label: '서쪽 아래 관문', x: 110, y: 530, kind: 'base' },
    { id: 'west-top', label: '서쪽 위 거점', x: 300, y: 220, kind: 'base' },
    { id: 'west-bottom', label: '서쪽 아래 거점', x: 300, y: 420, kind: 'base' },
    { id: 'drum-nw', label: '북서쪽 북', x: 330, y: 90, kind: 'special' },
    { id: 'drum-sw', label: '남서쪽 북', x: 330, y: 550, kind: 'special' },
    { id: 'bridge-top', label: '위쪽 다리', x: 550, y: 110, kind: 'base' },
    { id: 'bridge-center', label: '가운데 다리', x: 550, y: 320, kind: 'base' },
    { id: 'bridge-bottom', label: '아래쪽 다리', x: 550, y: 530, kind: 'base' },
    { id: 'drum-ne', label: '북동쪽 북', x: 770, y: 90, kind: 'special' },
    { id: 'drum-se', label: '남동쪽 북', x: 770, y: 550, kind: 'special' },
    { id: 'east-top', label: '동쪽 위 거점', x: 800, y: 220, kind: 'base' },
    { id: 'east-bottom', label: '동쪽 아래 거점', x: 800, y: 420, kind: 'base' },
    { id: 'red-top', label: '동쪽 위 관문', x: 990, y: 110, kind: 'base' },
    { id: 'red-bottom', label: '동쪽 아래 관문', x: 990, y: 530, kind: 'base' },
    { id: 'hq-red', label: '빨강 본부', x: 990, y: 320, kind: 'hq', ownerIndex: 1 },
  ],
  edges: [
    ['hq-blue', 'blue-top'], ['hq-blue', 'blue-bottom'],
    ['blue-top', 'west-top'], ['blue-bottom', 'west-bottom'],
    ['west-top', 'west-bottom'],
    ['west-top', 'drum-nw'], ['drum-nw', 'bridge-top'],
    ['west-bottom', 'drum-sw'], ['drum-sw', 'bridge-bottom'],
    ['west-top', 'bridge-top'], ['west-top', 'bridge-center'],
    ['west-bottom', 'bridge-center'], ['west-bottom', 'bridge-bottom'],
    ['hq-red', 'red-top'], ['hq-red', 'red-bottom'],
    ['red-top', 'east-top'], ['red-bottom', 'east-bottom'],
    ['east-top', 'east-bottom'],
    ['east-top', 'drum-ne'], ['drum-ne', 'bridge-top'],
    ['east-bottom', 'drum-se'], ['drum-se', 'bridge-bottom'],
    ['east-top', 'bridge-top'], ['east-top', 'bridge-center'],
    ['east-bottom', 'bridge-center'], ['east-bottom', 'bridge-bottom'],
  ],
  regions: [
    { id: 'northwest', nodeIds: ['west-top', 'drum-nw', 'bridge-top'], medals: 1, x: 398, y: 137 },
    { id: 'southwest', nodeIds: ['west-bottom', 'drum-sw', 'bridge-bottom'], medals: 1, x: 398, y: 503 },
    { id: 'west', nodeIds: ['west-top', 'west-bottom', 'bridge-center'], medals: 3, x: 390, y: 320 },
    { id: 'north', nodeIds: ['bridge-top', 'east-top', 'bridge-center', 'west-top'], medals: 2, x: 550, y: 215 },
    { id: 'south', nodeIds: ['bridge-bottom', 'west-bottom', 'bridge-center', 'east-bottom'], medals: 2, x: 550, y: 425 },
    { id: 'northeast', nodeIds: ['east-top', 'drum-ne', 'bridge-top'], medals: 1, x: 702, y: 137 },
    { id: 'southeast', nodeIds: ['east-bottom', 'drum-se', 'bridge-bottom'], medals: 1, x: 702, y: 503 },
    { id: 'east', nodeIds: ['east-top', 'east-bottom', 'bridge-center'], medals: 3, x: 710, y: 320 },
  ],
  // The centre bridge is already the fight for medals; the depots pull play toward the wings.
  depots: ['bridge-top', 'bridge-bottom'],
};

// Each terrain has its own board: different bases, different roads, different scoring
// regions. Nodes are listed west to east so the lobby preview seeds blue on the left.

export const TROPICAL_MAP: GameMap = {
  id: 'tropical-pool',
  name: '열대 수영장',
  width: 1100,
  height: 640,
  medalTarget: 6,
  theme: 'tropical',
  description: '위아래 풀장 가장자리를 돌거나, 힘이 맞는 병정으로 섬을 밟고 가운데를 가로지르는 전장.',
  specialDescription: '숫자가 적힌 섬 거점에는 그 힘의 병정 또는 조커만 놓을 수 있습니다.',
  nodes: [
    { id: 'hq-blue', label: '파랑 본부', x: 110, y: 320, kind: 'hq', ownerIndex: 0 },
    { id: 'deck-west-top', label: '서쪽 위 선베드', x: 230, y: 170, kind: 'base' },
    { id: 'deck-west-bottom', label: '서쪽 아래 선베드', x: 230, y: 470, kind: 'base' },
    { id: 'poolside-nw', label: '북서 풀 가장자리', x: 390, y: 90, kind: 'base' },
    { id: 'poolside-sw', label: '남서 풀 가장자리', x: 390, y: 550, kind: 'base' },
    { id: 'island-1', label: '힘 1 섬', x: 420, y: 235, kind: 'special', requiredPower: 1 },
    { id: 'island-3', label: '힘 3 섬', x: 420, y: 405, kind: 'special', requiredPower: 3 },
    { id: 'poolside-n', label: '북쪽 미끄럼틀', x: 550, y: 70, kind: 'base' },
    { id: 'diving-board', label: '다이빙대', x: 550, y: 320, kind: 'base' },
    { id: 'poolside-s', label: '남쪽 미끄럼틀', x: 550, y: 570, kind: 'base' },
    { id: 'island-5', label: '힘 5 섬', x: 680, y: 235, kind: 'special', requiredPower: 5 },
    { id: 'island-7', label: '힘 7 섬', x: 680, y: 405, kind: 'special', requiredPower: 7 },
    { id: 'poolside-ne', label: '북동 풀 가장자리', x: 710, y: 90, kind: 'base' },
    { id: 'poolside-se', label: '남동 풀 가장자리', x: 710, y: 550, kind: 'base' },
    { id: 'deck-east-top', label: '동쪽 위 선베드', x: 870, y: 170, kind: 'base' },
    { id: 'deck-east-bottom', label: '동쪽 아래 선베드', x: 870, y: 470, kind: 'base' },
    { id: 'hq-red', label: '빨강 본부', x: 990, y: 320, kind: 'hq', ownerIndex: 1 },
  ],
  edges: [
    ['hq-blue', 'deck-west-top'], ['hq-blue', 'deck-west-bottom'],
    ['deck-west-top', 'poolside-nw'], ['deck-west-top', 'island-1'],
    ['deck-west-bottom', 'poolside-sw'], ['deck-west-bottom', 'island-3'],
    ['poolside-nw', 'poolside-n'], ['poolside-n', 'poolside-ne'],
    ['poolside-sw', 'poolside-s'], ['poolside-s', 'poolside-se'],
    ['poolside-nw', 'island-1'], ['poolside-sw', 'island-3'],
    ['poolside-ne', 'island-5'], ['poolside-se', 'island-7'],
    ['island-1', 'diving-board'], ['island-3', 'diving-board'],
    ['island-5', 'diving-board'], ['island-7', 'diving-board'],
    ['hq-red', 'deck-east-top'], ['hq-red', 'deck-east-bottom'],
    ['deck-east-top', 'poolside-ne'], ['deck-east-top', 'island-5'],
    ['deck-east-bottom', 'poolside-se'], ['deck-east-bottom', 'island-7'],
  ],
  regions: [
    { id: 'northwest', nodeIds: ['deck-west-top', 'poolside-nw', 'island-1'], medals: 1, x: 347, y: 165 },
    { id: 'southwest', nodeIds: ['deck-west-bottom', 'poolside-sw', 'island-3'], medals: 1, x: 347, y: 475 },
    { id: 'west-basin', nodeIds: ['deck-west-top', 'island-1', 'island-3', 'deck-west-bottom'], medals: 2, x: 320, y: 320 },
    { id: 'north-lagoon', nodeIds: ['island-1', 'poolside-n', 'island-5', 'diving-board'], medals: 3, x: 550, y: 210 },
    { id: 'south-lagoon', nodeIds: ['island-3', 'diving-board', 'island-7', 'poolside-s'], medals: 3, x: 550, y: 430 },
    { id: 'east-basin', nodeIds: ['island-5', 'deck-east-top', 'deck-east-bottom', 'island-7'], medals: 2, x: 780, y: 320 },
    { id: 'northeast', nodeIds: ['island-5', 'poolside-ne', 'deck-east-top'], medals: 1, x: 753, y: 165 },
    { id: 'southeast', nodeIds: ['island-7', 'poolside-se', 'deck-east-bottom'], medals: 1, x: 753, y: 475 },
  ],
  depots: ['poolside-n', 'poolside-s'],
};

export const CLOUD_MAP: GameMap = {
  id: 'city-of-clouds',
  name: '구름 정원',
  width: 1100,
  height: 640,
  medalTarget: 6,
  theme: 'cloud',
  description: '가운데 하늘길은 네 걸음이면 건너지만 막히기 쉽고, 구름을 돌아가면 병정을 보충할 수 있는 전장.',
  specialDescription: '노란 구름 거점에 병정을 놓으면 병정 더미에서 1개를 뽑습니다.',
  nodes: [
    { id: 'hq-blue', label: '파랑 본부', x: 110, y: 320, kind: 'hq', ownerIndex: 0 },
    { id: 'cloud-nw', label: '북서 구름', x: 230, y: 140, kind: 'special' },
    { id: 'cloud-sw', label: '남서 구름', x: 230, y: 500, kind: 'special' },
    { id: 'sky-west', label: '서쪽 하늘길', x: 300, y: 320, kind: 'base' },
    { id: 'step-nw', label: '북서 디딤돌', x: 420, y: 170, kind: 'base' },
    { id: 'step-sw', label: '남서 디딤돌', x: 420, y: 470, kind: 'base' },
    { id: 'sky-west-center', label: '서쪽 가운데 하늘길', x: 460, y: 320, kind: 'base' },
    { id: 'cloud-n', label: '북쪽 구름', x: 550, y: 80, kind: 'special' },
    { id: 'cloud-s', label: '남쪽 구름', x: 550, y: 560, kind: 'special' },
    { id: 'sky-east-center', label: '동쪽 가운데 하늘길', x: 640, y: 320, kind: 'base' },
    { id: 'step-ne', label: '북동 디딤돌', x: 680, y: 170, kind: 'base' },
    { id: 'step-se', label: '남동 디딤돌', x: 680, y: 470, kind: 'base' },
    { id: 'sky-east', label: '동쪽 하늘길', x: 800, y: 320, kind: 'base' },
    { id: 'cloud-ne', label: '북동 구름', x: 870, y: 140, kind: 'special' },
    { id: 'cloud-se', label: '남동 구름', x: 870, y: 500, kind: 'special' },
    { id: 'hq-red', label: '빨강 본부', x: 990, y: 320, kind: 'hq', ownerIndex: 1 },
  ],
  edges: [
    ['hq-blue', 'sky-west'], ['hq-blue', 'cloud-nw'], ['hq-blue', 'cloud-sw'],
    ['cloud-nw', 'sky-west'], ['cloud-sw', 'sky-west'],
    ['cloud-nw', 'step-nw'], ['cloud-sw', 'step-sw'],
    ['sky-west', 'step-nw'], ['sky-west', 'step-sw'],
    ['sky-west', 'sky-west-center'], ['sky-west-center', 'sky-east-center'], ['sky-east-center', 'sky-east'],
    ['step-nw', 'cloud-n'], ['step-sw', 'cloud-s'],
    ['step-nw', 'sky-west-center'], ['step-sw', 'sky-west-center'],
    ['cloud-n', 'step-ne'], ['cloud-s', 'step-se'],
    ['step-ne', 'sky-east-center'], ['step-se', 'sky-east-center'],
    ['step-ne', 'sky-east'], ['step-se', 'sky-east'],
    ['step-ne', 'cloud-ne'], ['step-se', 'cloud-se'],
    ['cloud-ne', 'sky-east'], ['cloud-se', 'sky-east'],
    ['hq-red', 'sky-east'], ['hq-red', 'cloud-ne'], ['hq-red', 'cloud-se'],
  ],
  regions: [
    { id: 'northwest', nodeIds: ['cloud-nw', 'step-nw', 'sky-west'], medals: 1, x: 317, y: 210 },
    { id: 'southwest', nodeIds: ['cloud-sw', 'step-sw', 'sky-west'], medals: 1, x: 317, y: 430 },
    { id: 'west', nodeIds: ['sky-west', 'step-nw', 'sky-west-center', 'step-sw'], medals: 2, x: 395, y: 262 },
    { id: 'north', nodeIds: ['step-nw', 'cloud-n', 'step-ne', 'sky-east-center', 'sky-west-center'], medals: 3, x: 550, y: 200 },
    { id: 'south', nodeIds: ['step-sw', 'sky-west-center', 'sky-east-center', 'step-se', 'cloud-s'], medals: 3, x: 550, y: 440 },
    { id: 'east', nodeIds: ['sky-east', 'step-ne', 'sky-east-center', 'step-se'], medals: 2, x: 705, y: 378 },
    { id: 'northeast', nodeIds: ['cloud-ne', 'step-ne', 'sky-east'], medals: 1, x: 783, y: 210 },
    { id: 'southeast', nodeIds: ['cloud-se', 'step-se', 'sky-east'], medals: 1, x: 783, y: 430 },
  ],
  depots: ['step-nw', 'step-se'],
};

export const JUNGLE_MAP: GameMap = {
  id: 'volcanic-jungle',
  name: '용암 정글',
  width: 1100,
  height: 640,
  medalTarget: 7,
  theme: 'jungle',
  description: '촘촘한 오솔길이 분화구를 감싸고 있어 밀어내기 한 번에 길이 뒤집히는 전장.',
  specialDescription: '용암 거점에 놓으면 인접한 적 병정 하나를 이 거점의 다른 인접 거점으로 밀 수 있습니다.',
  nodes: [
    { id: 'hq-blue', label: '파랑 본부', x: 110, y: 320, kind: 'hq', ownerIndex: 0 },
    { id: 'trail-w1', label: '서쪽 위 오솔길', x: 240, y: 190, kind: 'base' },
    { id: 'trail-w2', label: '서쪽 아래 오솔길', x: 240, y: 450, kind: 'base' },
    { id: 'trail-w3', label: '북서 덤불', x: 370, y: 110, kind: 'base' },
    { id: 'trail-w4', label: '서쪽 공터', x: 370, y: 320, kind: 'base' },
    { id: 'trail-w5', label: '남서 덤불', x: 370, y: 530, kind: 'base' },
    { id: 'lava-nw', label: '북서 용암', x: 480, y: 220, kind: 'special' },
    { id: 'lava-sw', label: '남서 용암', x: 480, y: 420, kind: 'special' },
    { id: 'canopy-n', label: '북쪽 나무 위', x: 550, y: 90, kind: 'base' },
    { id: 'crater', label: '분화구', x: 550, y: 320, kind: 'base' },
    { id: 'canopy-s', label: '남쪽 나무 위', x: 550, y: 550, kind: 'base' },
    { id: 'lava-ne', label: '북동 용암', x: 620, y: 220, kind: 'special' },
    { id: 'lava-se', label: '남동 용암', x: 620, y: 420, kind: 'special' },
    { id: 'trail-e3', label: '북동 덤불', x: 730, y: 110, kind: 'base' },
    { id: 'trail-e4', label: '동쪽 공터', x: 730, y: 320, kind: 'base' },
    { id: 'trail-e5', label: '남동 덤불', x: 730, y: 530, kind: 'base' },
    { id: 'trail-e1', label: '동쪽 위 오솔길', x: 860, y: 190, kind: 'base' },
    { id: 'trail-e2', label: '동쪽 아래 오솔길', x: 860, y: 450, kind: 'base' },
    { id: 'hq-red', label: '빨강 본부', x: 990, y: 320, kind: 'hq', ownerIndex: 1 },
  ],
  edges: [
    ['hq-blue', 'trail-w1'], ['hq-blue', 'trail-w2'],
    ['trail-w1', 'trail-w3'], ['trail-w1', 'trail-w4'], ['trail-w2', 'trail-w4'], ['trail-w2', 'trail-w5'],
    ['trail-w3', 'canopy-n'], ['trail-w3', 'lava-nw'],
    ['trail-w4', 'lava-nw'], ['trail-w4', 'lava-sw'],
    ['trail-w5', 'lava-sw'], ['trail-w5', 'canopy-s'],
    ['canopy-n', 'lava-nw'], ['canopy-n', 'lava-ne'],
    ['canopy-s', 'lava-sw'], ['canopy-s', 'lava-se'],
    ['lava-nw', 'crater'], ['lava-sw', 'crater'], ['lava-ne', 'crater'], ['lava-se', 'crater'],
    ['trail-e3', 'canopy-n'], ['trail-e3', 'lava-ne'],
    ['trail-e4', 'lava-ne'], ['trail-e4', 'lava-se'],
    ['trail-e5', 'lava-se'], ['trail-e5', 'canopy-s'],
    ['trail-e1', 'trail-e3'], ['trail-e1', 'trail-e4'], ['trail-e2', 'trail-e4'], ['trail-e2', 'trail-e5'],
    ['hq-red', 'trail-e1'], ['hq-red', 'trail-e2'],
  ],
  regions: [
    { id: 'northwest', nodeIds: ['trail-w3', 'canopy-n', 'lava-nw'], medals: 1, x: 467, y: 140 },
    { id: 'southwest', nodeIds: ['trail-w5', 'lava-sw', 'canopy-s'], medals: 1, x: 467, y: 500 },
    { id: 'west-slope', nodeIds: ['trail-w4', 'lava-nw', 'crater', 'lava-sw'], medals: 3, x: 470, y: 320 },
    { id: 'north-slope', nodeIds: ['lava-nw', 'lava-ne', 'crater'], medals: 2, x: 550, y: 235 },
    { id: 'south-slope', nodeIds: ['lava-sw', 'crater', 'lava-se'], medals: 2, x: 550, y: 405 },
    { id: 'east-slope', nodeIds: ['lava-ne', 'trail-e4', 'lava-se', 'crater'], medals: 3, x: 630, y: 320 },
    { id: 'northeast', nodeIds: ['canopy-n', 'trail-e3', 'lava-ne'], medals: 1, x: 633, y: 140 },
    { id: 'southeast', nodeIds: ['lava-se', 'trail-e5', 'canopy-s'], medals: 1, x: 633, y: 500 },
  ],
  depots: ['canopy-n', 'canopy-s'],
};

export const CEMETERY_MAP: GameMap = {
  id: 'cursed-cemetery',
  name: '저주받은 묘지',
  width: 1100,
  height: 640,
  medalTarget: 6,
  theme: 'cemetery',
  description: '위아래로 길게 도는 묘지 길과 예배당을 지나는 가운데 길이 있고, 버린 병정을 다시 손에 드는 전장.',
  specialDescription: '묘지 거점에 놓으면 버림 더미의 내 병정 하나를 손으로 데려옵니다.',
  nodes: [
    { id: 'hq-blue', label: '파랑 본부', x: 110, y: 320, kind: 'hq', ownerIndex: 0 },
    { id: 'path-n1', label: '서쪽 철문', x: 250, y: 190, kind: 'base' },
    { id: 'path-s1', label: '서쪽 쪽문', x: 250, y: 450, kind: 'base' },
    { id: 'path-n2', label: '북서 비석 길', x: 400, y: 100, kind: 'base' },
    { id: 'grave-west', label: '서쪽 묘지', x: 400, y: 320, kind: 'special' },
    { id: 'path-s2', label: '남서 비석 길', x: 400, y: 540, kind: 'base' },
    { id: 'path-n3', label: '북쪽 고목', x: 550, y: 80, kind: 'base' },
    { id: 'chapel', label: '예배당', x: 550, y: 320, kind: 'base' },
    { id: 'path-s3', label: '남쪽 고목', x: 550, y: 560, kind: 'base' },
    { id: 'path-n4', label: '북동 비석 길', x: 700, y: 100, kind: 'base' },
    { id: 'grave-east', label: '동쪽 묘지', x: 700, y: 320, kind: 'special' },
    { id: 'path-s4', label: '남동 비석 길', x: 700, y: 540, kind: 'base' },
    { id: 'path-n5', label: '동쪽 철문', x: 850, y: 190, kind: 'base' },
    { id: 'path-s5', label: '동쪽 쪽문', x: 850, y: 450, kind: 'base' },
    { id: 'hq-red', label: '빨강 본부', x: 990, y: 320, kind: 'hq', ownerIndex: 1 },
  ],
  edges: [
    ['hq-blue', 'path-n1'], ['hq-blue', 'path-s1'],
    ['path-n1', 'path-n2'], ['path-n2', 'path-n3'], ['path-n3', 'path-n4'], ['path-n4', 'path-n5'],
    ['path-s1', 'path-s2'], ['path-s2', 'path-s3'], ['path-s3', 'path-s4'], ['path-s4', 'path-s5'],
    ['path-n1', 'grave-west'], ['path-s1', 'grave-west'],
    ['path-n2', 'grave-west'], ['path-s2', 'grave-west'],
    ['grave-west', 'chapel'], ['chapel', 'grave-east'],
    ['path-n3', 'chapel'], ['path-s3', 'chapel'],
    ['path-n4', 'grave-east'], ['path-s4', 'grave-east'],
    ['path-n5', 'grave-east'], ['path-s5', 'grave-east'],
    ['hq-red', 'path-n5'], ['hq-red', 'path-s5'],
  ],
  regions: [
    { id: 'northwest', nodeIds: ['path-n1', 'path-n2', 'grave-west'], medals: 1, x: 350, y: 203 },
    { id: 'southwest', nodeIds: ['path-s1', 'grave-west', 'path-s2'], medals: 1, x: 350, y: 437 },
    { id: 'north-west-crypt', nodeIds: ['path-n2', 'path-n3', 'chapel', 'grave-west'], medals: 2, x: 475, y: 205 },
    { id: 'south-west-crypt', nodeIds: ['path-s2', 'grave-west', 'chapel', 'path-s3'], medals: 2, x: 475, y: 435 },
    { id: 'north-east-crypt', nodeIds: ['path-n3', 'path-n4', 'grave-east', 'chapel'], medals: 2, x: 625, y: 205 },
    { id: 'south-east-crypt', nodeIds: ['path-s3', 'chapel', 'grave-east', 'path-s4'], medals: 2, x: 625, y: 435 },
    { id: 'northeast', nodeIds: ['path-n4', 'path-n5', 'grave-east'], medals: 1, x: 750, y: 203 },
    { id: 'southeast', nodeIds: ['path-s4', 'grave-east', 'path-s5'], medals: 1, x: 750, y: 437 },
  ],
  depots: ['path-n3', 'path-s3'],
};

export const CARIBBEAN_MAP: GameMap = {
  id: 'caribbean-sea',
  name: '카리브 해',
  width: 1100,
  height: 640,
  medalTarget: 7,
  theme: 'caribbean',
  description: '파랑은 북쪽과 남쪽 두 항구에서 출항하고, 빨강은 동쪽 요새 하나를 지키는 비대칭 해상 전장.',
  specialDescription: '특수 거점은 없습니다. 파랑은 두 본부 중 어느 곳에서든 길을 이어 갈 수 있고, 빨강은 둘 중 한 곳만 점령해도 승리합니다.',
  nodes: [
    { id: 'hq-blue', label: '파랑 북쪽 항구', x: 110, y: 140, kind: 'hq', ownerIndex: 0 },
    { id: 'hq-blue-south', label: '파랑 남쪽 항구', x: 110, y: 500, kind: 'hq', ownerIndex: 0 },
    { id: 'pier-north', label: '북쪽 부두', x: 260, y: 110, kind: 'base' },
    { id: 'cove', label: '서쪽 만', x: 240, y: 320, kind: 'base' },
    { id: 'pier-south', label: '남쪽 부두', x: 260, y: 530, kind: 'base' },
    { id: 'isle-nw', label: '북서 섬', x: 400, y: 200, kind: 'base' },
    { id: 'isle-sw', label: '남서 섬', x: 400, y: 440, kind: 'base' },
    { id: 'isle-n', label: '북쪽 산호섬', x: 560, y: 90, kind: 'base' },
    { id: 'reef', label: '가운데 암초', x: 560, y: 320, kind: 'base' },
    { id: 'isle-s', label: '남쪽 산호섬', x: 560, y: 550, kind: 'base' },
    { id: 'isle-ne', label: '북동 섬', x: 720, y: 200, kind: 'base' },
    { id: 'isle-se', label: '남동 섬', x: 720, y: 440, kind: 'base' },
    { id: 'fort-north', label: '북쪽 포대', x: 860, y: 170, kind: 'base' },
    { id: 'fort-south', label: '남쪽 포대', x: 860, y: 470, kind: 'base' },
    { id: 'hq-red', label: '빨강 요새', x: 990, y: 320, kind: 'hq', ownerIndex: 1 },
  ],
  edges: [
    ['hq-blue', 'pier-north'], ['hq-blue', 'cove'],
    ['hq-blue-south', 'pier-south'], ['hq-blue-south', 'cove'],
    ['pier-north', 'isle-nw'], ['pier-north', 'isle-n'],
    ['pier-south', 'isle-sw'], ['pier-south', 'isle-s'],
    ['cove', 'isle-nw'], ['cove', 'isle-sw'],
    ['isle-nw', 'isle-n'], ['isle-sw', 'isle-s'],
    ['isle-nw', 'reef'], ['isle-sw', 'reef'],
    ['isle-n', 'isle-ne'], ['isle-s', 'isle-se'],
    ['reef', 'isle-ne'], ['reef', 'isle-se'],
    ['isle-ne', 'fort-north'], ['isle-se', 'fort-south'],
    ['fort-north', 'fort-south'],
    ['hq-red', 'fort-north'], ['hq-red', 'fort-south'],
  ],
  regions: [
    { id: 'north-harbor', nodeIds: ['pier-north', 'isle-nw', 'cove'], medals: 1, x: 300, y: 210 },
    { id: 'south-harbor', nodeIds: ['pier-south', 'cove', 'isle-sw'], medals: 1, x: 300, y: 430 },
    { id: 'west-strait', nodeIds: ['cove', 'isle-nw', 'reef', 'isle-sw'], medals: 3, x: 400, y: 320 },
    { id: 'north-sea', nodeIds: ['isle-nw', 'isle-n', 'isle-ne', 'reef'], medals: 2, x: 560, y: 205 },
    { id: 'south-sea', nodeIds: ['isle-sw', 'reef', 'isle-se', 'isle-s'], medals: 2, x: 560, y: 435 },
    { id: 'fort-bay', nodeIds: ['isle-ne', 'fort-north', 'fort-south', 'isle-se'], medals: 3, x: 790, y: 320 },
    { id: 'northeast', nodeIds: ['isle-n', 'fort-north', 'isle-ne'], medals: 1, x: 713, y: 153 },
    { id: 'southeast', nodeIds: ['isle-s', 'isle-se', 'fort-south'], medals: 1, x: 713, y: 487 },
  ],
  depots: ['isle-n', 'isle-s'],
};

export const STATION_MAP: GameMap = {
  id: 'station-metal-x',
  name: '우주정거장 메탈-X',
  width: 1100,
  height: 640,
  medalTarget: 7,
  theme: 'station',
  description: '바깥 통로를 돌아가거나 능력이 멈추는 금속 통로를 지나 중앙 코어로 들어가는 전장.',
  specialDescription: '금속 거점에 놓인 병정은 소환 능력을 사용하지 않습니다.',
  nodes: [
    { id: 'hq-blue', label: '파랑 본부', x: 110, y: 320, kind: 'hq', ownerIndex: 0 },
    { id: 'dock-nw', label: '북서 도킹 베이', x: 240, y: 180, kind: 'base' },
    { id: 'dock-sw', label: '남서 도킹 베이', x: 240, y: 460, kind: 'base' },
    { id: 'ring-n1', label: '북서 바깥 통로', x: 380, y: 110, kind: 'base' },
    { id: 'metal-west', label: '서쪽 금속 통로', x: 380, y: 320, kind: 'special' },
    { id: 'ring-s1', label: '남서 바깥 통로', x: 380, y: 530, kind: 'base' },
    { id: 'ring-n2', label: '북쪽 바깥 통로', x: 550, y: 80, kind: 'base' },
    { id: 'metal-north', label: '북쪽 금속 통로', x: 550, y: 190, kind: 'special' },
    { id: 'core', label: '중앙 코어', x: 550, y: 320, kind: 'base' },
    { id: 'metal-south', label: '남쪽 금속 통로', x: 550, y: 450, kind: 'special' },
    { id: 'ring-s2', label: '남쪽 바깥 통로', x: 550, y: 560, kind: 'base' },
    { id: 'ring-n3', label: '북동 바깥 통로', x: 720, y: 110, kind: 'base' },
    { id: 'metal-east', label: '동쪽 금속 통로', x: 720, y: 320, kind: 'special' },
    { id: 'ring-s3', label: '남동 바깥 통로', x: 720, y: 530, kind: 'base' },
    { id: 'dock-ne', label: '북동 도킹 베이', x: 860, y: 180, kind: 'base' },
    { id: 'dock-se', label: '남동 도킹 베이', x: 860, y: 460, kind: 'base' },
    { id: 'hq-red', label: '빨강 본부', x: 990, y: 320, kind: 'hq', ownerIndex: 1 },
  ],
  edges: [
    ['hq-blue', 'dock-nw'], ['hq-blue', 'dock-sw'],
    ['dock-nw', 'ring-n1'], ['dock-sw', 'ring-s1'],
    ['dock-nw', 'metal-west'], ['dock-sw', 'metal-west'],
    ['ring-n1', 'ring-n2'], ['ring-n2', 'ring-n3'],
    ['ring-s1', 'ring-s2'], ['ring-s2', 'ring-s3'],
    ['ring-n2', 'metal-north'], ['ring-s2', 'metal-south'],
    ['metal-west', 'core'], ['metal-north', 'core'], ['metal-south', 'core'], ['metal-east', 'core'],
    ['ring-n3', 'dock-ne'], ['ring-s3', 'dock-se'],
    ['dock-ne', 'metal-east'], ['dock-se', 'metal-east'],
    ['hq-red', 'dock-ne'], ['hq-red', 'dock-se'],
  ],
  regions: [
    { id: 'northwest', nodeIds: ['dock-nw', 'ring-n1', 'metal-west'], medals: 1, x: 333, y: 203 },
    { id: 'southwest', nodeIds: ['dock-sw', 'metal-west', 'ring-s1'], medals: 1, x: 333, y: 437 },
    { id: 'north-ring', nodeIds: ['ring-n1', 'ring-n2', 'ring-n3', 'metal-north'], medals: 2, x: 550, y: 135 },
    { id: 'south-ring', nodeIds: ['ring-s1', 'metal-south', 'ring-s3', 'ring-s2'], medals: 2, x: 550, y: 505 },
    { id: 'west-core', nodeIds: ['metal-west', 'metal-north', 'core'], medals: 1, x: 493, y: 277 },
    { id: 'north-core', nodeIds: ['metal-north', 'metal-east', 'core'], medals: 2, x: 607, y: 277 },
    { id: 'south-core', nodeIds: ['metal-west', 'core', 'metal-south'], medals: 2, x: 493, y: 363 },
    { id: 'east-core', nodeIds: ['core', 'metal-east', 'metal-south'], medals: 1, x: 607, y: 363 },
    { id: 'northeast', nodeIds: ['ring-n3', 'dock-ne', 'metal-east'], medals: 1, x: 767, y: 203 },
    { id: 'southeast', nodeIds: ['metal-east', 'dock-se', 'ring-s3'], medals: 1, x: 767, y: 437 },
  ],
  depots: ['ring-n2', 'ring-s2'],
};

export const BATTLEFIELD_MAP: GameMap = {
  id: 'battlefield',
  name: '사막 참호',
  width: 1100,
  height: 640,
  medalTarget: 7,
  theme: 'battlefield',
  description: '포탄 구덩이를 지나야 닿는 가운데 벙커를 두고 참호가 마주 보며, 상대 손패를 묶어 다음 수를 흔드는 전장.',
  specialDescription: '참호 거점에 놓으면 상대의 뒷면 손패 한 장을 고릅니다. 그 병정은 상대의 다음 차례에 놓을 수 없고 차례가 끝나면 다시 사용할 수 있습니다.',
  nodes: [
    { id: 'hq-blue', label: '파랑 본부', x: 110, y: 320, kind: 'hq', ownerIndex: 0 },
    { id: 'line-w-top', label: '서쪽 위 진지', x: 250, y: 170, kind: 'base' },
    { id: 'line-w-bottom', label: '서쪽 아래 진지', x: 250, y: 470, kind: 'base' },
    { id: 'trench-nw', label: '북서 참호', x: 400, y: 100, kind: 'special' },
    { id: 'line-w-mid', label: '서쪽 전선', x: 400, y: 320, kind: 'base' },
    { id: 'trench-sw', label: '남서 참호', x: 400, y: 540, kind: 'special' },
    { id: 'crater-n', label: '북쪽 포탄 구덩이', x: 550, y: 200, kind: 'base' },
    { id: 'bunker', label: '가운데 벙커', x: 550, y: 320, kind: 'base' },
    { id: 'crater-s', label: '남쪽 포탄 구덩이', x: 550, y: 440, kind: 'base' },
    { id: 'trench-ne', label: '북동 참호', x: 700, y: 100, kind: 'special' },
    { id: 'line-e-mid', label: '동쪽 전선', x: 700, y: 320, kind: 'base' },
    { id: 'trench-se', label: '남동 참호', x: 700, y: 540, kind: 'special' },
    { id: 'line-e-top', label: '동쪽 위 진지', x: 850, y: 170, kind: 'base' },
    { id: 'line-e-bottom', label: '동쪽 아래 진지', x: 850, y: 470, kind: 'base' },
    { id: 'hq-red', label: '빨강 본부', x: 990, y: 320, kind: 'hq', ownerIndex: 1 },
  ],
  edges: [
    ['hq-blue', 'line-w-top'], ['hq-blue', 'line-w-bottom'],
    ['line-w-top', 'trench-nw'], ['line-w-top', 'line-w-mid'],
    ['line-w-bottom', 'line-w-mid'], ['line-w-bottom', 'trench-sw'],
    ['trench-nw', 'crater-n'], ['trench-sw', 'crater-s'],
    ['line-w-mid', 'crater-n'], ['line-w-mid', 'crater-s'],
    ['crater-n', 'bunker'], ['crater-s', 'bunker'],
    ['trench-nw', 'trench-ne'], ['trench-sw', 'trench-se'],
    ['trench-ne', 'crater-n'], ['trench-se', 'crater-s'],
    ['line-e-mid', 'crater-n'], ['line-e-mid', 'crater-s'],
    ['line-e-top', 'trench-ne'], ['line-e-top', 'line-e-mid'],
    ['line-e-bottom', 'line-e-mid'], ['line-e-bottom', 'trench-se'],
    ['hq-red', 'line-e-top'], ['hq-red', 'line-e-bottom'],
  ],
  regions: [
    { id: 'northwest', nodeIds: ['line-w-top', 'trench-nw', 'line-w-mid'], medals: 1, x: 350, y: 197 },
    { id: 'southwest', nodeIds: ['line-w-bottom', 'line-w-mid', 'trench-sw'], medals: 1, x: 350, y: 443 },
    { id: 'north-sap', nodeIds: ['trench-nw', 'trench-ne', 'crater-n'], medals: 2, x: 550, y: 140 },
    { id: 'south-sap', nodeIds: ['trench-sw', 'crater-s', 'trench-se'], medals: 2, x: 550, y: 500 },
    { id: 'west-front', nodeIds: ['line-w-mid', 'crater-n', 'bunker', 'crater-s'], medals: 3, x: 470, y: 320 },
    { id: 'east-front', nodeIds: ['crater-n', 'line-e-mid', 'crater-s', 'bunker'], medals: 3, x: 630, y: 320 },
    { id: 'northeast', nodeIds: ['trench-ne', 'line-e-top', 'line-e-mid'], medals: 1, x: 750, y: 197 },
    { id: 'southeast', nodeIds: ['line-e-mid', 'line-e-bottom', 'trench-se'], medals: 1, x: 750, y: 443 },
  ],
  depots: ['crater-n', 'crater-s'],
};

export const GAME_MAPS: GameMap[] = [CASTLE_MAP, TROPICAL_MAP, CLOUD_MAP, JUNGLE_MAP, CEMETERY_MAP, CARIBBEAN_MAP, STATION_MAP, BATTLEFIELD_MAP];
export const MAP_BY_ID: Record<string, GameMap> = Object.fromEntries(GAME_MAPS.map(map => [map.id, map]));
export const getMap = (id: string): GameMap => MAP_BY_ID[id] ?? CASTLE_MAP;
export const nodeIndex = (map: GameMap): Record<string, GameMap['nodes'][number]> => Object.fromEntries(map.nodes.map(node => [node.id, node]));
export const adjacency = (map: GameMap): Record<string, string[]> => Object.fromEntries(
  map.nodes.map(node => [node.id, map.edges.flatMap(([a, b]) => a === node.id ? [b] : b === node.id ? [a] : [])]),
);

export const edgeKey = (a: string, b: string, map: GameMap = CASTLE_MAP): string => {
  const [x, y] = map.edges.find(([p, q]) => (p === a && q === b) || (p === b && q === a)) ?? [a, b];
  return `${x}|${y}`;
};

export const NODE_BY_ID = nodeIndex(CASTLE_MAP);
export const ADJACENCY = adjacency(CASTLE_MAP);
